### ISSUE TITLE
Button notifucation

### ISSUE THREAD

**Issue by gde-pass** [gde-pass/Matcha#29]
Le bouton de notification est visible meme sans être connecté

**Comment by kandeol** [comment]
Effectivement , lorsque l'on se déconnecte on est renvoyé sur l'index .
Le bouton recherche est aussi encore actif.

ils faudrait lorsque l'on se delog être redirigé vers la page login , comme au 1er lancement du site.

**Comment by kandeol** [comment]
c'est bon j'ai réglé la redirection
